# dir and file names for geoclimatic data
geoclim:
  dir:
    main: geoclim
    gps_data: geospatial
    climate_data: climate
  files:
    raw_table: coff_madag_species_summary.xlsx
    gps_all: species_locations_all_positions.csv
    gbs_filtered: species_locations_gbs_only.csv

# Dir and file names for genetic data
genetic:
  dir:
    main: genetic
    gbs_full : gbs_full
    gbs_trimmed: gbs_trimmed
  files:
    full_concat_fasta: coffea_gbs.fasta
    trimmed_concat_fasta: coffea_gbs_trimmed.fasta

# URLs for data
URLs:
  madaclim_current: http://madaclim.cirad.fr/climate/current.tif
  

# User parameters
params:
  bp_to_keep: 1000
