# Filenames of genetic and climate data
input_filenames:
  concat_fasta: placeholder #TODO give name when implemented
  GPS_in: species_locations # No extension

# Trimmed data directories
trimmed_dirs:
  GBS_in: GBS_trimmed

# Trimmed filenames
trimmed_filenames:
  concat_fasta: coffea_GBS_trimmed.fasta  #No extension

# User parameters
genetic:
  bp_to_keep: 1000
#TODO implement modulable params for calculations

