# Filenames of genetic and climate data
input_filenames:
  concat_fasta: placeholder #TODO give name when implemented
  gps_in: species_locations.csv
  raw_table: coff_madag_species_summary.xlsx

# Trimmed data directories
trimmed_dirs:
  gbs_in: gbs_trimmed

# Trimmed filenames
trimmed_filenames:
  concat_fasta: coffea_gbs_trimmed.fasta

# User parameters
genetic:
  bp_to_keep: 1000
#TODO implement modulable params for calculations

