# dir and file names for geoclimatic data
geoclim:
  dir:
    gps_data: geospatial
  files:
    raw_table: coff_madag_species_summary.xlsx
    gps_in: species_locations.csv

# Dir and file names for genetic data
genetic:
  dir:
    gbs_full : gbs
    gbs_trimmed: gbs_trimmed
files:
  full_concat_fasta: coffea_gbs.fasta
  trimmed_concat_fasta: coffea_gbs_trimmed.fasta


# User parameters
params:
  bp_to_keep: 1000
