[project]
name = "py_madaclim"
version = "0.1.0"
license = {file = "LICENSE.txt"}
dynamic = ["readme"]

[tool.setuptools.packages.find]
where =["src"]

[tool.setuptools.dynamic]
readme = {file = "README.md"}