# Outside package directories
outside_dirs:
  data: data
  scripts: scripts

# dir and file names for geoclimatic data
geoclim:
  dir:
    main: geoclim
    gps_data: geospatial
    climate_data: climate
    environment_data: enviro
  files:
    raw_table: coff_madag_species_summary.xlsx
    gps_all: species_locations_all_positions.csv
    gbs_filtered: species_locations_gbs_only.csv
    madaclim_current: madaclim_current.tif
    madaclim_enviro: madaclim_enviro.tif
    clim_metadata: clim_metadata.json
    env_metadata: enviro_metadata.json
    clim_data_format: clim_data_format.json
    env_data_format: env_data_format.json

# Dir and file names for genetic data
genetic:
  dir:
    main: genetic
    gbs_full : gbs_full
    gbs_trimmed: gbs_trimmed
  files:
    full_concat_fasta: coffea_gbs.fasta
    trimmed_concat_fasta: coffea_gbs_trimmed.fasta

# URLs for data
urls:
  madaclim_current_raster: http://madaclim.cirad.fr/climate/current.tif
  environment_raster: http://madaclim.cirad.fr/environ/environ.tif
  clim_methods: https://madaclim.cirad.fr/methods-climate/
  env_methods: https://madaclim.cirad.fr/methods-environ-data/
  clim_data_format: https://madaclim.cirad.fr/climate-data-format/
  env_data_format: https://madaclim.cirad.fr/environ-data-format/

# User parameters
params:
  bp_to_keep: 1000
